### PR TITLE
Update dependencies and use app router

### PR DESCRIPTION
**Pull request by masterHAWK99**
- [x] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [x] Other

## Summary

 I've updated next and all relevant dependencies. Also used app router and improved the project structure a little bit.

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
This one is big. I'd rather move to he app router after we finish with the exam mode since there are contributors working on this app.

**Comment by eduardconstantin** [comment]
I will try to make some time this weekend to check the changes

**Comment by eduardconstantin** [comment]
@masterHAWK99 there are some conflicts, could you fix them? I would like to merge this PR next week

**Comment by eduardconstantin** [comment]
I checked the changes and I get some warnings in the console
image

**Comment by masterHAWK99** [comment]
@eduardconstantin Sorry for the delay in my response. I managed to fix those warnings and also updated Next to the latest version. 

I was unable to reproduce the bug where the answer remains selected after reveal. My suggestion would be to create an issue for that, as I don't believe this PR introduced that behavior and it is already quite extensive.

**Comment by eduardconstantin** [comment]
@masterHAWK99 no worries! I checked the changes and everything looks great. Whatever you did seem to have fixed the issue in the practice mode.

**Review by eduardconstantin — APPROVED** [review]
Thank you for your contributions!

**Pull request merged**
