### PR TITLE
Fix reveal answer remains selected

### LINKED ISSUE #86: [BUG] Reveal answer remains selected
**Describe the bug**
In practice mode, if I press reveal answer button and I change the question number at the top of the page the option remains selected for all the questions.

**To Reproduce**
1. Go to Practice mode
2. Click on Reveal Answer
3. Change question number at the top of the page

**Expected behavior**
When the question changes no option should be selected or revealed

### PR DESCRIPTION
**Pull request by adripo**
Fixes #86 

- [x] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [x] Bug fix (please link related issues if applicable)
- [ ] New feature
- [ ] Question update
- [ ] Other

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
This fixed the bug, but if I reveal the question move to the next page or any other page, reveal the question again and go back I don't see the previous selections.
If I press reveal answer I should see the correct answer for the previous questions.

**Comment by eduardconstantin** [comment]
I'll have a better look tomorrow.

**Comment by adripo** [comment]
@eduardconstantin I think I managed to solve the issue.

**Comment by eduardconstantin** [comment]
now the option I select remains selected, which is good but the correct answer is not displayed.
This is how it looks:
image
And this is how it should look:
image

Also, if I go back I shouldn't be able to reveal the question again since it is already revealed

**Comment by adripo** [comment]
Now I understood the correct behavior. This last commit should fix it.

**Review by eduardconstantin — APPROVED** [review]
Now it works like a charm! Thank you!

**Pull request merged**
