### PR TITLE
Added Missing details in Exam Complition UI

### LINKED ISSUE #63: [Feature] Exam mode completion UI
**Is your feature request related to a problem? Please describe.**
As a student preparing for the Azure Fundamentals certification, I value a user-friendly and engaging interface when I finish the exam mode. This is the last screen in the exam mode.

**Describe the solution you'd like**
To enhance the exam experience, the completion screen need to be implemented which includes the following components:
- **Exam status:** A text that show if the exam has been passed or not. The color of the text should be green if the exam is passed and red if not.
- **Points:** A text showing the number of points the user has made "X/100". Same as the exam status the points should be colored green if the exam has been passed or red if not.
- **Completion message:** A text showing the user a congratulatory message and the amount of time it took to pass the exam. If the exam is failed it should tell the user the minimum amount of points needed to pass the exam.
- **Retake Exam Button:** A clearly labeled "Retake exam" button should be provided for the user to let him retake the exam with new random questions.

**Additional context**

image
image

You can find the link to figma file [here.](https://www.figma.com/file/ckNeex3dSR7Y32bPfJHiQQ/Azure-Fundamentals?type=design&node-id=417%3A10&mode=design&t=iEDVcKy710touMia-1)

### PR DESCRIPTION
**Pull request by SAGARSINGH-1**
Fixes #63 

- [X] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

Added those features: 

● Paragraph Missing
● Number of Questions Missing
● Time Information Missing

### CODE REVIEW

**Comment by eduardconstantin** [comment]
When I fail the exam I get the completion screen inside the quiz screen, I assume the same happens when I pass the exam
image

I think you only have to look at spaces and to center the render text under the points

**Comment by SAGARSINGH-1** [comment]
I'll look on that.

**Review by masterHAWK99 — COMMENTED** [review]
Now there's problem with:
image

I think it's because width doesn't scale.

**Comment by SAGARSINGH-1** [comment]
@masterHAWK99 Yes, I'm on my laptop, and I set the width and forgot to remove it.

**Review by masterHAWK99 — COMMENTED** [review]
Unfortunately, the problem still exists.
image

**Comment by SAGARSINGH-1** [comment]
How can I setup it in my local system I have this error : 

image

**Comment by eduardconstantin** [comment]
I tried it locally too, it works fine for me, make sure you pull the latest changes from dev branch

**Comment by SAGARSINGH-1** [comment]
no, i pull the latest but this is always showing every time run locally

**Comment by SAGARSINGH-1** [comment]
Any method to merge my PR please it's my last PR for Hacktoberfest how can I solve it plz help me out.

**Comment by eduardconstantin** [comment]
so you didn't manage to debug the error. I will take a look this week.

**Comment by SAGARSINGH-1** [comment]
Please. I didn't find why in my local system the error showed up.

**Comment by eduardconstantin** [comment]
I can't push my changes to your branch. 
I will merge it like this and I will fix it tomorrow.

**Review by eduardconstantin — APPROVED** [review]

**Pull request merged**
