### PR TITLE
Fix question index numbering

### LINKED ISSUE #66: [BUG] Questions index should start from 1
**Describe the bug**
In Practice or Exam mode questions index starts from 0

**To Reproduce**
1. Go to Practice or Exam mode
2. In Practice you can see it starts from 0, in Exam after "Begin exam" is clicked, on the right side is "0/30"

**Expected behavior**
Questions index should start from 1, not 0

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by sushma1031**
Fixes #66 

- [x] I have read and agree to the [Code of Conduct](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](https://github.com/eduardconstantin/azure-fundamentals/blob/main/CONTRIBUTING.md).

## Pull Request Type

- [x] Bug fix (please link related issues if applicable)

## Summary

Updated the numbering of exam and practice questions to begin from 1 instead of 0.
Also changed the `range` parameter in `pages/exam/index.ts` to fetch 30 questions instead of 31.

### Before clicking `Begin`

Screenshot (151)

### After clicking `Begin`

Screenshot (152)

### Practice
Screenshot (153)

### CODE REVIEW

**Review by eduardconstantin — COMMENTED** [review]
It seems ok, @masterHAWK99 can you double check?
Also there is one minor bug. In practice mode, when I try to add 0 here
image
I get an error
image

**Comment by sushma1031** [comment]
Oh, right, I'll fix that.

**Comment by masterHAWK99** [comment]
Unfortunately in practice mode when you reach the last question and click the next question you start over and the index become 1.

**Comment by eduardconstantin** [comment]
> Unfortunately in practice mode when you reach the last question and click the next question you start over and the index become 1.

For practice mode that should be the desired functionality, but the options should not be selected

**Comment by sushma1031** [comment]
@eduardconstantin I fixed the 0 value bug, anything else I should change?

**Review by eduardconstantin — APPROVED** [review]
Looks good to me! Thank you for your contribution!

**Pull request merged**
